-- Seeds for users table

insert into users ( name, email, phone, password) values ( 'Zio', '1@2', '888-196-8197','123');
insert into users ( name, email, phone, password) values ( 'Vera', '1@3', '360-465-0385','234');
insert into users ( name, email, phone, password) values ( 'Prudi', '1@1', '888-196-8197','123');
insert into users ( name, email, phone, password) values ( 'Lorilee', 'lnorquoy2@sina.com.cn', '910-996-1354','123');
insert into users ( name, email, phone, password) values ( 'Malva', 'mcockett3@ox.ac.uk', '996-654-5074','123');
insert into users ( name, email, phone, password) values ( 'Constantine', 'ckirckman4@examiner.com', '314-631-6635','123');
insert into users ( name, email, phone, password) values ( 'Sander', 'sdehailes5@altervista.org', '292-488-7431','123');
insert into users ( name, email, phone, password) values ( 'Hortensia', 'hpochon6@oaic.gov.au', '882-260-0806','123');
insert into users ( name, email, phone, password) values ( 'Morgan', 'mcurm7@sfgate.com', '237-791-1502','456');
insert into users ( name, email, phone, password) values ( 'Buck', 'boakden8@quantcast.com', '972-500-3144','456');


-- Seeds for products table

insert into products (user_id,name, description, price, image_path) values (1,'Catnips 3lbs', 'Keep your kitty active and engaged with this Whisker City Cactus Compressed Catnip Cat Toy. A touch of catnip makes this fun toy even better. ', 6.99, '/images/catMint.jpg');
insert into products (user_id, name, description, price, image_path) values (2,'LitterEasy', 'This Exquisicat Rimmed Litter Pan helps to reduce litter scatter because of its snap-on rim.You will love it because it keeps litter where it belongs;in the litter pan.', 9.2, '/images/litterbox.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Little Companion', 'Our Elephant Dog Toy is detailed with tiny limbs, soft to the touch and squeaks for added entertainment. Keep him active with fun toys; an active dog is a healthy dog. ', 9, '/images/dogAndToy.jpg');
insert into products (user_id, name, description, price, image_path) values (4,'Bonding Bites', 'Natural snack for dogs made from a single ingredient: 100% sweet potato of Peruvian origin.', 17.9, '/images/dogFood.jpg');
insert into products (user_id, name, description, price, image_path) values (1,'Dogsour', 'Finally! A plush toy that lasts! KONGs Plush Dinosour Squeaker Dog Toy is the perfect toy for your pooch who loves stuffed toys - minus the mess! This plush toy comes with a pre-loaded removable internal squeaker that all dogs love.', 28, '/images/dogAndDinosour.jpg');
insert into products (user_id, name, description, price, image_path) values (2,'Whisker City', 'Your cat will love spending time on this Whisker City Wicker Short Cat Tower. This tower provides the perfect perch on which your kitty can absorb the world around her.', 119.99, '/images/furniture.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Fresh Breath Dental Sticks', 'Fresh Breath by TropiClean offers many solutions to help make your dogs dental care routine easier! Treat your dog to a healthy mouth with Fresh Breath by TropiClean Dental Sticks. By treating your dog to one Fresh Breath Dental Stick each day, you can support his oral health and give him fresh breat - no brushing required. These grain & gluten-free, easily digestible Dental Sticks for small dogs have a tasty Vanilla Mint flavor, and a unique chewy texture that helps brush away plaque & tartar and provide fresh breath for dogs with each bite.', 15, '/images/treats.jpg');
insert into products (user_id, name, description, price, image_path) values (1,'Ah Rubber Duck!','Who said only software developers love rubber ducks? Your dog too!Buy them some so that your duck will still be available to be told codes to.' , 15, '/images/dogAndRubberDuck.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Soft Bed','Who said only software developers love rubber ducks? Your dog too!Buy them some so that your duck will still be available to be told codes to.' , 15, '/images/bed.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Cactus Tree','Who said only software developers love rubber ducks? Your dog too!Buy them some so that your duck will still be available to be told codes to.' , 85, '/images/chewy.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Shampoo','Who said only software developers love rubber ducks? Your dog too!Buy them some so that your duck will still be available to be told codes to.' , 25, '/images/chewy.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Homemade Cat Treats','Who said only software developers love rubber ducks? Your dog too!Buy them some so that your duck will still be available to be told codes to.' , 28, '/images/delicious.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Little Fish Food Container','Who said only software developers love rubber ducks? Your dog too!Buy them some so that your duck will still be available to be told codes to.' , 28, '/images/foodContainer.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Litter Robot','If you are a cool programmer, buy your cat a cool litter robot! One, this AI litterbos makes you and your cat keep growing at the same pace. Two, you can talk to the robot when your rubber duck is teared by your dog, again.' , 158, '/images/litterRobot.jpg');
insert into products (user_id, name, description, price, image_path) values (3,'Little Comfort Sheep','Keep your loved one warm and comfy.' , 28, '/images/sheepToy.jpg');

-- Seeds for services table
insert into services (user_id, name, description, price, image_path, lat, lng) values (1,'Cats Grooming', 'Making cats look great is our passion!  We offer complete bath & haircut services and walk-in services. Book your pet salon appointment today!', 59, '/images/catGrooming.jpg', 49.222566,-122.937695);
insert into services (user_id, name, description, price, image_path, lat, lng) values (2,'Dogs Grooming', ' Our academy-trained Pet Stylists have over 800 hours of hands-on grooming instruction that includes bathing, trimming & styling at least 200 dogs of all breeds & sizes plus annual safety certification. ', 59, '/images/dogGrooming.jpg', 49.20787431462918, -122.92302659886583);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Cats training', 'Our famous cat training classes can help them learn how to behave appropriately at home and on-the-go. Our Accredited Pet Trainers teach fun & eﬀective group & private classes through positive reinforcement.', 599, '/images/catTyping.jpg', 49.272610628514784, -123.24488907436151);
insert into services (user_id, name, description, price, image_path, lat, lng) values (4,'Dogs training', 'Whether you have a young pup, older dog or a rescue, our dog training classes can help them learn how to behave appropriately at home and on-the-go. Our Accredited Pet Trainers teach fun & eﬀective group & private classes through positive reinforcement.', 59, '/images/dogTraining.jpg',49.214318970093395, -123.00310394881708);
insert into services (user_id, name, description, price, image_path, lat, lng) values (1,'Cats walking', 'Every cat walker on the site has been hand-reviewed and approved by the Rover team. They’ve also completed a general background check.', 30, '/images/catWalker.jpg', 49.33165099336615, -123.10539385419389);
insert into services (user_id, name, description, price, image_path, lat, lng) values (2,'Dogs walking', ' Our academy-trained Pet Stylists have over 800 hours of hands-on grooming instruction that includes bathing, trimming & styling at least 200 dogs of all breeds & sizes plus annual safety certification.', 30, '/images/dogWalker.jpg', 49.25798367961171, -123.10640006213352);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'dog Hotel', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 109, '/images/dogHotelBed.jpg',49.28321168623181, -122.78057502494524);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Dog Intellegence Development', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 129, '/images/bianmu.jpg',49.28321168623181, -122.78057502494524);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Vet Service', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 699, '/images/vet.jpg',49.28321168623181, -122.78057502494524);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Dog Web Development Bootcamp', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 12229, '/images/dogLearningCs.jpg',49.28321168623181, -122.78057502494524);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Diet Planning', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 129, '/images/foodwithdogfeet.jpg',49.28321168623181, -122.78057502494524);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Clean & Happy', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 69, '/images/shower.jpg',49.28321168623181, -122.78057502494524);
insert into services (user_id, name, description, price, image_path, lat, lng) values (3,'Learning Swimming', 'Our comfortable accommodations & safety-certified associates provide a welcoming place for dogs & cats to stay while you’re away! Guests will feel at home with the around-the-clock care of our pet-loving staff. We offer a safe, clean, temperature-controlled environment, playtime, exercise, healthy meals & more. Book the ultimate staycation destination for your pet now!', 399, '/images/dogHotel.jpg',49.28321168623181, -122.78057502494524);



INSERT INTO messages (sender_id, recipient_id, content)
VALUES (1, 2, 'Is it still available?');
INSERT INTO messages (sender_id, recipient_id, content)
VALUES (2, 1, 'Yes. I have many in stock');
INSERT INTO messages (sender_id, recipient_id, content)
VALUES (1, 2, 'Will you negotiate on the price?');
INSERT INTO messages (sender_id, recipient_id, content)
VALUES (2, 1, 'Sorry, this is the lowest price I could offer.');
